# Generated by Django 5.2.1 on 2025-06-02 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_notifier_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=100)),
                ("channel_name", models.CharField(max_length=255)),
                ("subscribers", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LanguageInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.CharField(max_length=10)),
                ("subtitles", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_id", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField()),
                ("thumbnail", models.URLField()),
                ("channel_name", models.CharField(max_length=255)),
                ("channel_id", models.CharField(max_length=100)),
                ("subscribers", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("entertainment", "Entertainment"),
                            ("education", "Education"),
                            ("gaming", "Gaming"),
                            ("music", "Music"),
                            ("news", "News"),
                            ("tech", "Technology"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("duration", models.CharField(max_length=20)),
                ("duration_seconds", models.IntegerField()),
                ("views", models.CharField(max_length=50)),
                ("likes", models.CharField(max_length=50)),
                ("dislikes", models.CharField(max_length=50)),
                ("upload_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_notifier_app.channelinfo",
                    ),
                ),
                (
                    "languages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_notifier_app.languageinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
