# Generated by Django 5.2.1 on 2025-06-02 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_notifier_app", "0002_channelinfo_languageinfo_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="languages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_notifier_app.languageinfo",
            ),
        ),
    ]
